ui:
  - changed-files:
      - any-glob-to-any-file: src/components/**

content:
  - changed-files:
      - any-glob-to-any-file: src/content/**

styles:
  - changed-files:
      - any-glob-to-any-file:
          - src/app/globals.css
          - tailwind.config.*

config:
  - changed-files:
      - any-glob-to-any-file:
          - "*.config.*"
          - .github/**
          - biome.json
          - tsconfig.json

ci:
  - changed-files:
      - any-glob-to-any-file: .github/workflows/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - pnpm-lock.yaml
